language: node_js

os: linux

addons:
  chrome: stable

node_js:
  - "12.14.1"

install:
  - npm ci

script:
  - npm run lib:prod
  - CHROMIUM_BIN="/usr/bin/google-chrome" npm test
  - EXAMPLES_SCRIPTS_URL_PREFIX="https://dostaltomas.github.io/angularjs-date-parser" npm run docs:build

jobs:
  include:
    - stage: Github Deployment
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GH_TOKEN
        keep-history: true
        local_dir: "dist/docs"
        on:
          branch: master

    - stage: Deploy to NPM
      deploy:
        edge: true
        provider: npm
        email: "tomas.dostal@kpsys.cz"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          branch: master
